config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'
  resources :genres, only: [:create, :show, :new]

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre
    else
      render :new
    end
  end

  def genre_params
    params.require(:genre).
        permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @genres = Genre.all
    @movies = Movie.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/genres/new.html.erb
<%= form_for(@genre) do |f| %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>
<%= render @movies %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieMania</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>MovieMania</h1>

<div class="admin_links">
  <%= link_to 'Add Genre', new_genre_path %>
</div>
<br/>
<%= yield %>

</body>
</html>

app/views/movies/_movie.html.erb
<%= movie.name %>

app/views/movies/index.html.erb
<% @genres.each do |genre| %>
    <%= link_to genre.name, genre %>
<% end %>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>